#index:
#    path: /
#    controller: App\Controller\DefaultController::index
annonce:
  type: rest
  resource: App\Controller\AnnonceController
  prefix: /v1
  name_prefix: v1_
  defaults: {_format: json}